export enum ROUTES {
  HOME = 'home',
  LOGIN = 'login',
  LAUNCHPAD = 'launchpad',
  SERVICES = 'services',
  APPS = 'apps',
  ADMINS = 'admins',
  USERS = 'users',
  ROLES = 'roles',
  APIDOCS = 'apidocs',
  SCHEMAS = 'schema',
  DATA = 'data',
  FILES = 'files',
  SCRIPTS = 'scripts',
  CONFIG = 'config',
  PACKAGES = 'package-manager',
  LIMITS = 'limits',
  SCHEDULER = 'scheduler',
  REPORTS = 'reports',
  PASSWORD_RESET = 'password-reset',
}
